CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 accelerate launch --num_processes 8 --config_file ./zero1.yaml grpo_training.py \
    --model_name_or_path Qwen/Qwen2.5-3B-Instruct \
    --dataset_name Jiayi-Pan/Countdown-Tasks-3to4 \
    --per_device_train_batch_size 1 \
    --max_steps 500 \
    --save_steps 100 \
    --save_strategy steps \
    --max_prompt_length 256 \
    --max_completion_length 1012 \
    --output_dir outputs-grpo-qwen-v2 \
    --torch_dtype bfloat16 \
    --bf16 True \
    --report_to tensorboard \
    --remove_unused_columns False \
    --gradient_accumulation_steps 8 \
    --gradient_checkpointing True \
    --beta 0.001 \
    --learning_rate 5.0e-7 \
    --lr_scheduler_type cosine \
    --warmup_ratio 0.03 \
    --push_to_hub False \
    --use_vllm False > x_r1_0.5B_sampling.log 2>&1