CUDA_VISIBLE_DEVICES=1 python supervised_finetuning.py \
    --model_type chatglm \
    --model_name_or_path F:\\Models\\ChatGLM-3\\chatglm3-6b-base \
    --device_map cuda:0 \
    --device cuda:0 \
    --template_name chatglm3 \
    --train_file_dir ./data/finetune \
    --validation_file_dir ./data/finetune \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --do_train \
    --do_eval \
    --use_peft True \
    --max_train_samples 10000 \
    --max_eval_samples 10 \
    --model_max_length 4096 \
    --num_train_epochs 5 \
    --learning_rate 2e-5 \
    --warmup_ratio 0.05 \
    --weight_decay 0.05 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 50 \
    --evaluation_strategy steps \
    --save_steps 500 \
    --save_strategy steps \
    --save_total_limit 13 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 4 \
    --output_dir outputs-sft-chatglm3-knowyourself \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 64\
    --lora_alpha 64 \
    --lora_dropout 0.05 \
    --torch_dtype float16 \
    --fp16 \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True \
    --cache_dir ./cache
